[tool.poetry]
name = "tesseract-olap-demo"
version = "0.2.0"
description = ""
authors = ["Francisco Abarzua <git.id@frabarz.cl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
granian = "^1.1.2"
logiclayer = "^0.2.1"
logiclayer-complexity = "^0.4.1"
tesseract-olap = {extras = ["clickhouse"], version = "^0.8.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
